spring:
  application:
    name: S10_P
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbootdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 보안 정책으로 에러를 클라이언트에 보여주는 것이 막혀있어서 아래를 추가하면 확인할 수 있음
server:
  error:
    include-message: always
    include-binding-errors: always
